[hekad]
#maxprocs = 2
share_dir = "/opt/heka/share"

[LogstreamerInput]
log_directory = "/var/log"
file_match = 'auth\.log'

[PayloadEncoder]
append_newlines = false

[statsd_input]
type = "StatsdInput"
stat_accum_name = "stat_accumulator"

[stat_accumulator]
type = "StatAccumInput"
ticker_interval = 2
emit_in_fields = true

[stat_graph]
type = "SandboxFilter"
filename = "lua_filters/stat_graph.lua"
ticker_interval = 1
preserve_data = false
message_matcher = "Type == 'heka.statmetric'"

    [stat_graph.config]
    num_rows = 300
    secs_per_row = 1
    stats = "stats.gauges.nic.1.packets.100 rr ee"
    stat_labels = "test rr ee"
    preservation_version = 0

[DashboardOutput]
ticker_interval = 1

#[UdpOutput]
#message_matcher = "Type == 'heka.statmetric'"
#address = "localhost:1000"
#encoder = "PayloadEncoder"

[TcpInput]
address = "localhost:999"
parser_type = "token"
delimiter = "\n"

[LOGGER]
type = "TcpOutput"
address = "localhost:1001"
encoder = "PayloadEncoder"
message_matcher = "Type == 'heka.statmetric'"


